# Generated by Django 2.1.15 on 2020-10-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('userpw', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('birth', models.CharField(max_length=30)),
            ],
        ),
    ]
