# Generated by Django 2.1.15 on 2020-10-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='PhoneNumber',
        ),
    ]
