# Generated by Django 2.1.15 on 2020-10-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_member_phonenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateField()),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
