# Generated by Django 2.1.15 on 2020-10-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
